apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.port }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
