services:
  biaint-mongo:
    image: mongo:6.0
    restart: no
    env_file: api/.env_compose
    ports:
      - 27017:27017
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1s
      timeout: 1s
      retries: 5
  bia-integrator-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: bia-integrator-api
    env_file: api/.env_compose
    container_name: api
    hostname: api
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - biaint-mongo
    healthcheck:
      # !! important to sync services
      test: ["CMD", "wget", "-O", "-", "api:8080/openapi.json"]
      interval: 1s
      timeout: 10s
      retries: 10
  client-refresh:
    depends_on:
      bia-integrator-api:
        condition: service_healthy
    container_name: openapi-generator
    user: ${MY_UID}
    image: openapitools/openapi-generator-cli:v7.8.0
    # docker-entrypoint.sh does argument parsing in the entrypoint and only picks up the bash command
    #   so re-run after pulling openapi.json to have the right env setup
    command: bash -c "wget -q -O - api:8080/openapi.json > openapi.json && docker-entrypoint.sh generate --config openapi_config_python.yml -i openapi.json -g python -o python"
    working_dir: /mnt/share
    volumes:
      - ./clients:/mnt/share
    profiles:
      - codegen