services:
  biaint-mongo:
    image: mongo:6.0
    restart: no
    env_file: api/.env_compose
    ports:
      - 27017:27017
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1s
      timeout: 1s
      retries: 5
      # command: "mongod --config /etc/mongo.conf --oplogMinRetentionHours 10"
      # volumes:
      #   - "./.share/mongo.conf:/etc/mongo.conf"
      #     #- "./.share/keyfile.secret:/home/share/keyfile/keyfile.secret"
  bia-integrator-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: ghcr.io/bioimage-archive/bia-integrator-api:0.2.0
    env_file: api/.env_compose
    container_name: api
    hostname: api
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - biaint-mongo

volumes:
  api_data:
    #? do we always want a 'seed db'?
    #external: true
