# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AnnotationState(str, Enum):
    """
    AnnotationState
    """

    """
    allowed enum values
    """
    ACTIVE = 'active'
    DELETED = 'deleted'

    @classmethod
    def from_json(cls, json_str: str) -> AnnotationState:
        """Create an instance of AnnotationState from a JSON string"""
        return AnnotationState(json.loads(json_str))


