# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict, List, Optional
from pydantic import BaseModel, Field, StrictInt, conlist
from bia_integrator_api.models.bulk_operation_item import BulkOperationItem

class BulkOperationResponse(BaseModel):
    """
    BulkOperationResponse
    """
    items: conlist(BulkOperationItem) = Field(...)
    item_idx_by_status: Optional[Dict[str, conlist(StrictInt)]] = None
    __properties = ["items", "item_idx_by_status"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BulkOperationResponse:
        """Create an instance of BulkOperationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in item_idx_by_status (dict of array)
        _field_dict_of_array = {}
        if self.item_idx_by_status:
            for _key in self.item_idx_by_status:
                if self.item_idx_by_status[_key]:
                    _field_dict_of_array[_key] = [
                        _item.to_dict() for _item in self.item_idx_by_status[_key]
                    ]
            _dict['item_idx_by_status'] = _field_dict_of_array
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BulkOperationResponse:
        """Create an instance of BulkOperationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BulkOperationResponse.parse_obj(obj)

        _obj = BulkOperationResponse.parse_obj({
            "items": [BulkOperationItem.from_dict(_item) for _item in obj.get("items")] if obj.get("items") is not None else None,
            "item_idx_by_status": obj.get("item_idx_by_status")
        })
        return _obj


