# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from bia_integrator_api.models.affiliation import Affiliation
from bia_integrator_api.models.annotation_file_reference import AnnotationFileReference
from bia_integrator_api.models.annotation_method import AnnotationMethod
from bia_integrator_api.models.annotation_type import AnnotationType
from bia_integrator_api.models.authentication_token import AuthenticationToken
from bia_integrator_api.models.bio_sample import BioSample
from bia_integrator_api.models.body_register_user import BodyRegisterUser
from bia_integrator_api.models.channel import Channel
from bia_integrator_api.models.contributor import Contributor
from bia_integrator_api.models.derived_image import DerivedImage
from bia_integrator_api.models.experimental_imaging_dataset import ExperimentalImagingDataset
from bia_integrator_api.models.experimentally_captured_image import ExperimentallyCapturedImage
from bia_integrator_api.models.external_reference import ExternalReference
from bia_integrator_api.models.file_reference import FileReference
from bia_integrator_api.models.funding_body import FundingBody
from bia_integrator_api.models.grant import Grant
from bia_integrator_api.models.http_validation_error import HTTPValidationError
from bia_integrator_api.models.image_acquisition import ImageAcquisition
from bia_integrator_api.models.image_analysis_method import ImageAnalysisMethod
from bia_integrator_api.models.image_annotation_dataset import ImageAnnotationDataset
from bia_integrator_api.models.image_correlation_method import ImageCorrelationMethod
from bia_integrator_api.models.image_representation import ImageRepresentation
from bia_integrator_api.models.image_representation_use_type import ImageRepresentationUseType
from bia_integrator_api.models.licence_type import LicenceType
from bia_integrator_api.models.location_inner import LocationInner
from bia_integrator_api.models.model_metadata import ModelMetadata
from bia_integrator_api.models.publication import Publication
from bia_integrator_api.models.rendered_view import RenderedView
from bia_integrator_api.models.signal_channel_information import SignalChannelInformation
from bia_integrator_api.models.specimen import Specimen
from bia_integrator_api.models.specimen_growth_protocol import SpecimenGrowthProtocol
from bia_integrator_api.models.specimen_imaging_preparation_protocol import SpecimenImagingPreparationProtocol
from bia_integrator_api.models.study import Study
from bia_integrator_api.models.taxon import Taxon
from bia_integrator_api.models.validation_error import ValidationError
