# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from bia_integrator_api.models.annotation_method_type import AnnotationMethodType
from bia_integrator_api.models.annotation_source_indicator import AnnotationSourceIndicator
from bia_integrator_api.models.attribute import Attribute
from bia_integrator_api.models.model_metadata import ModelMetadata
from bia_integrator_api.models.provenance import Provenance
from typing import Optional, Set
from typing_extensions import Self

class AnnotationMethod(BaseModel):
    """
    AnnotationMethod
    """ # noqa: E501
    uuid: StrictStr = Field(description="Unique ID (across the BIA database) used to refer to and identify a document.")
    object_creator: Provenance
    version: Annotated[int, Field(strict=True, ge=0)] = Field(description="Document version. This can't be optional to make sure we never persist objects without it")
    model: Optional[ModelMetadata] = None
    additional_metadata: Optional[List[Attribute]] = Field(default=None, description="Freeform key-value pairs that don't otherwise fit our data model, potentially from user provided metadata, BIA curation, and experimental fields.")
    title: StrictStr = Field(description="The title of a protocol.")
    protocol_description: StrictStr = Field(description="Description of actions involved in the process.")
    annotation_criteria: Optional[StrictStr] = None
    annotation_coverage: Optional[StrictStr] = None
    transformation_description: Optional[StrictStr] = None
    spatial_information: Optional[StrictStr] = None
    method_type: List[AnnotationMethodType] = Field(description="Classification of the kind of annotation that was performed.")
    annotation_source_indicator: Optional[AnnotationSourceIndicator] = None
    __properties: ClassVar[List[str]] = ["uuid", "object_creator", "version", "model", "additional_metadata", "title", "protocol_description", "annotation_criteria", "annotation_coverage", "transformation_description", "spatial_information", "method_type", "annotation_source_indicator"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnnotationMethod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in additional_metadata (list)
        _items = []
        if self.additional_metadata:
            for _item_additional_metadata in self.additional_metadata:
                if _item_additional_metadata:
                    _items.append(_item_additional_metadata.to_dict())
            _dict['additional_metadata'] = _items
        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if annotation_criteria (nullable) is None
        # and model_fields_set contains the field
        if self.annotation_criteria is None and "annotation_criteria" in self.model_fields_set:
            _dict['annotation_criteria'] = None

        # set to None if annotation_coverage (nullable) is None
        # and model_fields_set contains the field
        if self.annotation_coverage is None and "annotation_coverage" in self.model_fields_set:
            _dict['annotation_coverage'] = None

        # set to None if transformation_description (nullable) is None
        # and model_fields_set contains the field
        if self.transformation_description is None and "transformation_description" in self.model_fields_set:
            _dict['transformation_description'] = None

        # set to None if spatial_information (nullable) is None
        # and model_fields_set contains the field
        if self.spatial_information is None and "spatial_information" in self.model_fields_set:
            _dict['spatial_information'] = None

        # set to None if annotation_source_indicator (nullable) is None
        # and model_fields_set contains the field
        if self.annotation_source_indicator is None and "annotation_source_indicator" in self.model_fields_set:
            _dict['annotation_source_indicator'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnnotationMethod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "object_creator": obj.get("object_creator"),
            "version": obj.get("version"),
            "model": ModelMetadata.from_dict(obj["model"]) if obj.get("model") is not None else None,
            "additional_metadata": [Attribute.from_dict(_item) for _item in obj["additional_metadata"]] if obj.get("additional_metadata") is not None else None,
            "title": obj.get("title"),
            "protocol_description": obj.get("protocol_description"),
            "annotation_criteria": obj.get("annotation_criteria"),
            "annotation_coverage": obj.get("annotation_coverage"),
            "transformation_description": obj.get("transformation_description"),
            "spatial_information": obj.get("spatial_information"),
            "method_type": obj.get("method_type"),
            "annotation_source_indicator": obj.get("annotation_source_indicator")
        })
        return _obj


