# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AnnotationSourceIndicator(str, Enum):
    """
    AnnotationSourceIndicator
    """

    """
    allowed enum values
    """
    METADATA_FILE = 'metadata_file'
    FILE_NAME_EXACT_MATCH = 'file_name_exact_match'
    FILE_NAME_PATTERN = 'file_name_pattern'
    FILE_PATH = 'file_path'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AnnotationSourceIndicator from a JSON string"""
        return cls(json.loads(json_str))


