# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from bia_integrator_api.models.model_metadata import ModelMetadata

class BIAImageOmeMetadata(BaseModel):
    """
    BIAImageOmeMetadata
    """
    uuid: StrictStr = Field(...)
    version: StrictInt = Field(...)
    model: Optional[ModelMetadata] = None
    bia_image_uuid: StrictStr = Field(...)
    ome_metadata: Dict[str, Any] = Field(..., description="The OME metadata as a json-compatible object. Can be used as a dictionary or directly parsed with the ome-types module.")
    __properties = ["uuid", "version", "model", "bia_image_uuid", "ome_metadata"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BIAImageOmeMetadata:
        """Create an instance of BIAImageOmeMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # set to None if model (nullable) is None
        # and __fields_set__ contains the field
        if self.model is None and "model" in self.__fields_set__:
            _dict['model'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BIAImageOmeMetadata:
        """Create an instance of BIAImageOmeMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BIAImageOmeMetadata.parse_obj(obj)

        _obj = BIAImageOmeMetadata.parse_obj({
            "uuid": obj.get("uuid"),
            "version": obj.get("version"),
            "model": ModelMetadata.from_dict(obj.get("model")) if obj.get("model") is not None else None,
            "bia_image_uuid": obj.get("bia_image_uuid"),
            "ome_metadata": obj.get("ome_metadata")
        })
        return _obj


