# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field

class BIACollection(BaseModel):
    """
    A collection of studies with a coherent purpose. Studies can be in multiple collections.
    """
    uuid: Optional[Any] = Field(...)
    version: Optional[Any] = Field(...)
    model: Optional[Any] = None
    name: Optional[Any] = Field(...)
    title: Optional[Any] = Field(...)
    subtitle: Optional[Any] = Field(...)
    description: Optional[Any] = None
    study_uuids: Optional[Any] = None
    additional_properties: Dict[str, Any] = {}
    __properties = ["uuid", "version", "model", "name", "title", "subtitle", "description", "study_uuids"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BIACollection:
        """Create an instance of BIACollection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if uuid (nullable) is None
        # and __fields_set__ contains the field
        if self.uuid is None and "uuid" in self.__fields_set__:
            _dict['uuid'] = None

        # set to None if version (nullable) is None
        # and __fields_set__ contains the field
        if self.version is None and "version" in self.__fields_set__:
            _dict['version'] = None

        # set to None if model (nullable) is None
        # and __fields_set__ contains the field
        if self.model is None and "model" in self.__fields_set__:
            _dict['model'] = None

        # set to None if name (nullable) is None
        # and __fields_set__ contains the field
        if self.name is None and "name" in self.__fields_set__:
            _dict['name'] = None

        # set to None if title (nullable) is None
        # and __fields_set__ contains the field
        if self.title is None and "title" in self.__fields_set__:
            _dict['title'] = None

        # set to None if subtitle (nullable) is None
        # and __fields_set__ contains the field
        if self.subtitle is None and "subtitle" in self.__fields_set__:
            _dict['subtitle'] = None

        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if study_uuids (nullable) is None
        # and __fields_set__ contains the field
        if self.study_uuids is None and "study_uuids" in self.__fields_set__:
            _dict['study_uuids'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BIACollection:
        """Create an instance of BIACollection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BIACollection.parse_obj(obj)

        _obj = BIACollection.parse_obj({
            "uuid": obj.get("uuid"),
            "version": obj.get("version"),
            "model": obj.get("model"),
            "name": obj.get("name"),
            "title": obj.get("title"),
            "subtitle": obj.get("subtitle"),
            "description": obj.get("description"),
            "study_uuids": obj.get("study_uuids")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


