# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field

class BodyRegisterUser(BaseModel):
    """
    BodyRegisterUser
    """
    email: Optional[Any] = Field(...)
    password_plain: Optional[Any] = Field(...)
    secret_token: Optional[Any] = Field(...)
    __properties = ["email", "password_plain", "secret_token"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BodyRegisterUser:
        """Create an instance of BodyRegisterUser from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if email (nullable) is None
        # and __fields_set__ contains the field
        if self.email is None and "email" in self.__fields_set__:
            _dict['email'] = None

        # set to None if password_plain (nullable) is None
        # and __fields_set__ contains the field
        if self.password_plain is None and "password_plain" in self.__fields_set__:
            _dict['password_plain'] = None

        # set to None if secret_token (nullable) is None
        # and __fields_set__ contains the field
        if self.secret_token is None and "secret_token" in self.__fields_set__:
            _dict['secret_token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BodyRegisterUser:
        """Create an instance of BodyRegisterUser from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BodyRegisterUser.parse_obj(obj)

        _obj = BodyRegisterUser.parse_obj({
            "email": obj.get("email"),
            "password_plain": obj.get("password_plain"),
            "secret_token": obj.get("secret_token")
        })
        return _obj


