# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field

class BulkOperationResponse(BaseModel):
    """
    BulkOperationResponse
    """
    items: Optional[Any] = Field(...)
    item_idx_by_status: Optional[Any] = Field(..., description="Utility for clients to easily assess if they should retry/correct some items")
    __properties = ["items", "item_idx_by_status"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BulkOperationResponse:
        """Create an instance of BulkOperationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "item_idx_by_status",
                          },
                          exclude_none=True)
        # set to None if items (nullable) is None
        # and __fields_set__ contains the field
        if self.items is None and "items" in self.__fields_set__:
            _dict['items'] = None

        # set to None if item_idx_by_status (nullable) is None
        # and __fields_set__ contains the field
        if self.item_idx_by_status is None and "item_idx_by_status" in self.__fields_set__:
            _dict['item_idx_by_status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BulkOperationResponse:
        """Create an instance of BulkOperationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BulkOperationResponse.parse_obj(obj)

        _obj = BulkOperationResponse.parse_obj({
            "items": obj.get("items"),
        })
        return _obj


