# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from bia_integrator_api.models.attribute import Attribute
from bia_integrator_api.models.model_metadata import ModelMetadata
from typing import Optional, Set
from typing_extensions import Self

class CreationProcess(BaseModel):
    """
    CreationProcess
    """ # noqa: E501
    uuid: StrictStr = Field(description="Unique ID (across the BIA database) used to refer to and identify a document.")
    version: Annotated[int, Field(strict=True, ge=0)] = Field(description="Document version. This can't be optional to make sure we never persist objects without it")
    model: Optional[ModelMetadata] = None
    attribute: Optional[List[Attribute]] = None
    subject_specimen_uuid: Optional[StrictStr] = None
    image_acquisition_protocol_uuid: Optional[List[StrictStr]] = None
    input_image_uuid: Optional[List[StrictStr]] = None
    protocol_uuid: Optional[List[StrictStr]] = None
    annotation_method_uuid: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["uuid", "version", "model", "attribute", "subject_specimen_uuid", "image_acquisition_protocol_uuid", "input_image_uuid", "protocol_uuid", "annotation_method_uuid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreationProcess from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attribute (list)
        _items = []
        if self.attribute:
            for _item_attribute in self.attribute:
                if _item_attribute:
                    _items.append(_item_attribute.to_dict())
            _dict['attribute'] = _items
        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if attribute (nullable) is None
        # and model_fields_set contains the field
        if self.attribute is None and "attribute" in self.model_fields_set:
            _dict['attribute'] = None

        # set to None if subject_specimen_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.subject_specimen_uuid is None and "subject_specimen_uuid" in self.model_fields_set:
            _dict['subject_specimen_uuid'] = None

        # set to None if image_acquisition_protocol_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.image_acquisition_protocol_uuid is None and "image_acquisition_protocol_uuid" in self.model_fields_set:
            _dict['image_acquisition_protocol_uuid'] = None

        # set to None if input_image_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.input_image_uuid is None and "input_image_uuid" in self.model_fields_set:
            _dict['input_image_uuid'] = None

        # set to None if protocol_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.protocol_uuid is None and "protocol_uuid" in self.model_fields_set:
            _dict['protocol_uuid'] = None

        # set to None if annotation_method_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.annotation_method_uuid is None and "annotation_method_uuid" in self.model_fields_set:
            _dict['annotation_method_uuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreationProcess from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "version": obj.get("version"),
            "model": ModelMetadata.from_dict(obj["model"]) if obj.get("model") is not None else None,
            "attribute": [Attribute.from_dict(_item) for _item in obj["attribute"]] if obj.get("attribute") is not None else None,
            "subject_specimen_uuid": obj.get("subject_specimen_uuid"),
            "image_acquisition_protocol_uuid": obj.get("image_acquisition_protocol_uuid"),
            "input_image_uuid": obj.get("input_image_uuid"),
            "protocol_uuid": obj.get("protocol_uuid"),
            "annotation_method_uuid": obj.get("annotation_method_uuid")
        })
        return _obj


