# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bia_integrator_api.models.attribute import Attribute
from typing import Optional, Set
from typing_extensions import Self

class ImageCorrelationMethod(BaseModel):
    """
    Information about the process of correlating the positions of multiple images.
    """ # noqa: E501
    attribute: Optional[List[Attribute]] = None
    protocol_description: StrictStr = Field(description="Description of actions involved in the process.")
    fiducials_used: StrictStr = Field(description="Features from correlated datasets used for colocalization.")
    transformation_matrix: StrictStr = Field(description="Correlation transforms.")
    __properties: ClassVar[List[str]] = ["attribute", "protocol_description", "fiducials_used", "transformation_matrix"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImageCorrelationMethod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attribute (list)
        _items = []
        if self.attribute:
            for _item_attribute in self.attribute:
                if _item_attribute:
                    _items.append(_item_attribute.to_dict())
            _dict['attribute'] = _items
        # set to None if attribute (nullable) is None
        # and model_fields_set contains the field
        if self.attribute is None and "attribute" in self.model_fields_set:
            _dict['attribute'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImageCorrelationMethod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attribute": [Attribute.from_dict(_item) for _item in obj["attribute"]] if obj.get("attribute") is not None else None,
            "protocol_description": obj.get("protocol_description"),
            "fiducials_used": obj.get("fiducials_used"),
            "transformation_matrix": obj.get("transformation_matrix")
        })
        return _obj


