# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LicenceType(str, Enum):
    """
    LicenceType
    """

    """
    allowed enum values
    """
    CC0 = 'CC0'
    CC_BY_4_DOT_0 = 'CC_BY_4.0'
    CC_BY_3_DOT_0 = 'CC_BY_3.0'
    CC_BY_2_DOT_5 = 'CC_BY_2.5'
    CC_BY_2_DOT_0 = 'CC_BY_2.0'
    CC_BY_1_DOT_0 = 'CC_BY_1.0'
    CC_BY_MINUS_SA_4_DOT_0 = 'CC_BY-SA_4.0'
    CC_BY_MINUS_SA_3_DOT_0 = 'CC_BY-SA_3.0'
    CC_BY_MINUS_SA_2_DOT_5 = 'CC_BY-SA_2.5'
    CC_BY_MINUS_SA_2_DOT_0 = 'CC_BY-SA_2.0'
    CC_BY_MINUS_SA_1_DOT_0 = 'CC_BY-SA_1.0'
    CC_BY_MINUS_SA_2_DOT_1_JP = 'CC_BY-SA_2.1_JP'
    CC_BY_MINUS_NC_4_DOT_0 = 'CC_BY-NC_4.0'
    CC_BY_MINUS_NC_3_DOT_0 = 'CC_BY-NC_3.0'
    CC_BY_MINUS_NC_2_DOT_5 = 'CC_BY-NC_2.5'
    CC_BY_MINUS_NC_2_DOT_0 = 'CC_BY-NC_2.0'
    CC_BY_MINUS_NC_1_DOT_0 = 'CC_BY-NC_1.0'
    CC_BY_MINUS_NC_MINUS_SA_4_DOT_0 = 'CC_BY-NC-SA_4.0'
    CC_BY_MINUS_NC_MINUS_SA_3_DOT_0 = 'CC_BY-NC-SA_3.0'
    CC_BY_MINUS_NC_MINUS_SA_2_DOT_5 = 'CC_BY-NC-SA_2.5'
    CC_BY_MINUS_NC_MINUS_SA_2_DOT_0 = 'CC_BY-NC-SA_2.0'
    CC_BY_MINUS_NC_MINUS_SA_1_DOT_0 = 'CC_BY-NC-SA_1.0'
    CC_BY_MINUS_NC_MINUS_ND_4_DOT_0 = 'CC_BY-NC-ND_4.0'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LicenceType from a JSON string"""
        return cls(json.loads(json_str))


