# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LicenceType(str, Enum):
    """
    LicenceType
    """

    """
    allowed enum values
    """
    CC0 = 'CC0'
    CC_BY_4_DOT_0 = 'CC_BY_4.0'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LicenceType from a JSON string"""
        return cls(json.loads(json_str))


