# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Licence(str, Enum):
    """
    Licence
    """

    """
    allowed enum values
    """
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_PUBLICDOMAIN_SLASH_ZERO_SLASH_1_DOT_0_SLASH = 'https://creativecommons.org/publicdomain/zero/1.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_SLASH_4_DOT_0_SLASH = 'https://creativecommons.org/licenses/by/4.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_SLASH_3_DOT_0_SLASH = 'https://creativecommons.org/licenses/by/3.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_SLASH_2_DOT_5_SLASH = 'https://creativecommons.org/licenses/by/2.5/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_SLASH_2_DOT_0_SLASH = 'https://creativecommons.org/licenses/by/2.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_SLASH_1_DOT_0_SLASH = 'https://creativecommons.org/licenses/by/1.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_SA_SLASH_4_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-sa/4.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_SA_SLASH_3_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-sa/3.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_SA_SLASH_2_DOT_5_SLASH = 'https://creativecommons.org/licenses/by-sa/2.5/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_SA_SLASH_2_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-sa/2.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_SA_SLASH_1_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-sa/1.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_SA_SLASH_2_DOT_1_SLASH_JP_SLASH = 'https://creativecommons.org/licenses/by-sa/2.1/jp/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_SLASH_4_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc/4.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_SLASH_3_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc/3.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_SLASH_2_DOT_5_SLASH = 'https://creativecommons.org/licenses/by-nc/2.5/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_SLASH_2_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc/2.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_SLASH_1_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc/1.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_MINUS_SA_SLASH_4_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc-sa/4.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_MINUS_SA_SLASH_3_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc-sa/3.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_MINUS_SA_SLASH_2_DOT_5_SLASH = 'https://creativecommons.org/licenses/by-nc-sa/2.5/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_MINUS_SA_SLASH_2_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc-sa/2.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_MINUS_SA_SLASH_1_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc-sa/1.0/'
    HTTPS_COLON_SLASH_SLASH_CREATIVECOMMONS_DOT_ORG_SLASH_LICENSES_SLASH_BY_MINUS_NC_MINUS_ND_SLASH_4_DOT_0_SLASH = 'https://creativecommons.org/licenses/by-nc-nd/4.0/'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Licence from a JSON string"""
        return cls(json.loads(json_str))


