# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bia_integrator_api.models.channel import Channel
from typing import Optional, Set
from typing_extensions import Self

class RenderedView(BaseModel):
    """
    A particular view of an image, such as as a specific timestamp of a time series, or a view direction of a 3D model.
    """ # noqa: E501
    z: Optional[StrictStr] = None
    t: Optional[StrictStr] = None
    channel_information: Optional[List[Channel]] = None
    __properties: ClassVar[List[str]] = ["z", "t", "channel_information"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RenderedView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in channel_information (list)
        _items = []
        if self.channel_information:
            for _item_channel_information in self.channel_information:
                if _item_channel_information:
                    _items.append(_item_channel_information.to_dict())
            _dict['channel_information'] = _items
        # set to None if z (nullable) is None
        # and model_fields_set contains the field
        if self.z is None and "z" in self.model_fields_set:
            _dict['z'] = None

        # set to None if t (nullable) is None
        # and model_fields_set contains the field
        if self.t is None and "t" in self.model_fields_set:
            _dict['t'] = None

        # set to None if channel_information (nullable) is None
        # and model_fields_set contains the field
        if self.channel_information is None and "channel_information" in self.model_fields_set:
            _dict['channel_information'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RenderedView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "z": obj.get("z"),
            "t": obj.get("t"),
            "channel_information": [Channel.from_dict(_item) for _item in obj["channel_information"]] if obj.get("channel_information") is not None else None
        })
        return _obj


