# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SearchFileRepresentation(BaseModel):
    """
    SearchFileRepresentation
    """ # noqa: E501
    size_bounds_lte: Optional[StrictInt] = None
    size_bounds_gte: Optional[StrictInt] = None
    type: Optional[StrictStr] = None
    uri_prefix: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["size_bounds_lte", "size_bounds_gte", "type", "uri_prefix"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchFileRepresentation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if size_bounds_lte (nullable) is None
        # and model_fields_set contains the field
        if self.size_bounds_lte is None and "size_bounds_lte" in self.model_fields_set:
            _dict['size_bounds_lte'] = None

        # set to None if size_bounds_gte (nullable) is None
        # and model_fields_set contains the field
        if self.size_bounds_gte is None and "size_bounds_gte" in self.model_fields_set:
            _dict['size_bounds_gte'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if uri_prefix (nullable) is None
        # and model_fields_set contains the field
        if self.uri_prefix is None and "uri_prefix" in self.model_fields_set:
            _dict['uri_prefix'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchFileRepresentation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "size_bounds_lte": obj.get("size_bounds_lte"),
            "size_bounds_gte": obj.get("size_bounds_gte"),
            "type": obj.get("type"),
            "uri_prefix": obj.get("uri_prefix")
        })
        return _obj


