# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field
from bia_integrator_api.models.annotation_state import AnnotationState

class StudyAnnotation(BaseModel):
    """
    StudyAnnotation
    """
    author_email: Optional[Any] = Field(...)
    key: Optional[Any] = Field(...)
    value: Optional[Any] = Field(...)
    state: AnnotationState = Field(...)
    __properties = ["author_email", "key", "value", "state"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StudyAnnotation:
        """Create an instance of StudyAnnotation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if author_email (nullable) is None
        # and __fields_set__ contains the field
        if self.author_email is None and "author_email" in self.__fields_set__:
            _dict['author_email'] = None

        # set to None if key (nullable) is None
        # and __fields_set__ contains the field
        if self.key is None and "key" in self.__fields_set__:
            _dict['key'] = None

        # set to None if value (nullable) is None
        # and __fields_set__ contains the field
        if self.value is None and "value" in self.__fields_set__:
            _dict['value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StudyAnnotation:
        """Create an instance of StudyAnnotation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StudyAnnotation.parse_obj(obj)

        _obj = StudyAnnotation.parse_obj({
            "author_email": obj.get("author_email"),
            "key": obj.get("key"),
            "value": obj.get("value"),
            "state": obj.get("state")
        })
        return _obj


