# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bia_integrator_api
from bia_integrator_api.models.annotation_state import AnnotationState  # noqa: E501
from bia_integrator_api.rest import ApiException

class TestAnnotationState(unittest.TestCase):
    """AnnotationState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationState(self):
        """Test AnnotationState"""
        # inst = AnnotationState()

if __name__ == '__main__':
    unittest.main()
