# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bia_integrator_api
from bia_integrator_api.models.body_register_user import BodyRegisterUser  # noqa: E501
from bia_integrator_api.rest import ApiException

class TestBodyRegisterUser(unittest.TestCase):
    """BodyRegisterUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyRegisterUser
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyRegisterUser`
        """
        model = bia_integrator_api.models.body_register_user.BodyRegisterUser()  # noqa: E501
        if include_optional :
            return BodyRegisterUser(
                email = '', 
                password_plain = '', 
                secret_token = ''
            )
        else :
            return BodyRegisterUser(
                email = '',
                password_plain = '',
                secret_token = '',
        )
        """

    def testBodyRegisterUser(self):
        """Test BodyRegisterUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
