# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bia_integrator_api
from bia_integrator_api.models.bia_image_representation_input import BIAImageRepresentationInput  # noqa: E501
from bia_integrator_api.rest import ApiException

class TestBIAImageRepresentationInput(unittest.TestCase):
    """BIAImageRepresentationInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BIAImageRepresentationInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BIAImageRepresentationInput`
        """
        model = bia_integrator_api.models.bia_image_representation_input.BIAImageRepresentationInput()  # noqa: E501
        if include_optional :
            return BIAImageRepresentationInput(
                size = None, 
                uri = None, 
                type = None, 
                dimensions = None, 
                attributes = None, 
                rendering = bia_integrator_api.models.rendering_info.RenderingInfo(
                    channel_renders = null, 
                    default_z = null, 
                    default_t = null, )
            )
        else :
            return BIAImageRepresentationInput(
                size = None,
        )
        """

    def testBIAImageRepresentationInput(self):
        """Test BIAImageRepresentationInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
