# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bia_integrator_api
from bia_integrator_api.models.bia_image_input import BIAImageInput  # noqa: E501
from bia_integrator_api.rest import ApiException

class TestBIAImageInput(unittest.TestCase):
    """BIAImageInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BIAImageInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BIAImageInput`
        """
        model = bia_integrator_api.models.bia_image_input.BIAImageInput()  # noqa: E501
        if include_optional :
            return BIAImageInput(
                uuid = None, 
                version = None, 
                model = None, 
                study_uuid = None, 
                original_relpath = None, 
                name = None, 
                dimensions = None, 
                representations = None, 
                attributes = None, 
                annotations = None, 
                alias = None
            )
        else :
            return BIAImageInput(
                uuid = None,
                version = None,
                study_uuid = None,
                original_relpath = None,
        )
        """

    def testBIAImageInput(self):
        """Test BIAImageInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
