# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import bia_integrator_api
from bia_integrator_api.models.bia_study_output import BIAStudyOutput  # noqa: E501
from bia_integrator_api.rest import ApiException

class TestBIAStudyOutput(unittest.TestCase):
    """BIAStudyOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BIAStudyOutput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BIAStudyOutput`
        """
        model = bia_integrator_api.models.bia_study_output.BIAStudyOutput()  # noqa: E501
        if include_optional :
            return BIAStudyOutput(
                uuid = None, 
                version = None, 
                model = None, 
                title = None, 
                description = None, 
                authors = None, 
                organism = None, 
                release_date = None, 
                accession_id = None, 
                imaging_type = None, 
                attributes = None, 
                annotations = None, 
                example_image_uri = None, 
                example_image_annotation_uri = None, 
                tags = None, 
                file_references_count = None, 
                images_count = None
            )
        else :
            return BIAStudyOutput(
                uuid = None,
                version = None,
                title = None,
                description = None,
                organism = None,
                release_date = None,
                accession_id = None,
        )
        """

    def testBIAStudyOutput(self):
        """Test BIAStudyOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
