# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.model_metadata import ModelMetadata

class BIACollection(BaseModel):
    """
    A collection of studies with a coherent purpose. Studies can be in multiple collections.
    """
    id: Optional[StrictStr] = Field(None, alias="_id")
    uuid: StrictStr = Field(...)
    version: StrictInt = Field(...)
    model: Optional[ModelMetadata] = None
    name: StrictStr = Field(...)
    title: StrictStr = Field(...)
    subtitle: StrictStr = Field(...)
    description: Optional[StrictStr] = None
    study_uuids: Optional[conlist(StrictStr)] = None
    __properties = ["_id", "uuid", "version", "model", "name", "title", "subtitle", "description", "study_uuids"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BIACollection:
        """Create an instance of BIACollection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BIACollection:
        """Create an instance of BIACollection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BIACollection.parse_obj(obj)

        _obj = BIACollection.parse_obj({
            "id": obj.get("_id"),
            "uuid": obj.get("uuid"),
            "version": obj.get("version"),
            "model": ModelMetadata.from_dict(obj.get("model")) if obj.get("model") is not None else None,
            "name": obj.get("name"),
            "title": obj.get("title"),
            "subtitle": obj.get("subtitle"),
            "description": obj.get("description"),
            "study_uuids": obj.get("study_uuids")
        })
        return _obj


