# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.file_reference import FileReference  # noqa: E501
from openapi_client.rest import ApiException

class TestFileReference(unittest.TestCase):
    """FileReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FileReference
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileReference`
        """
        model = openapi_client.models.file_reference.FileReference()  # noqa: E501
        if include_optional :
            return FileReference(
                id = '', 
                uuid = '', 
                version = 56, 
                model = openapi_client.models.model_metadata.ModelMetadata(
                    type_name = '', 
                    version = 56, ), 
                study_uuid = '', 
                name = '', 
                uri = '', 
                type = '', 
                size_bytes = 56, 
                attributes = openapi_client.models.attributes.Attributes()
            )
        else :
            return FileReference(
                uuid = '',
                version = 56,
                model = openapi_client.models.model_metadata.ModelMetadata(
                    type_name = '', 
                    version = 56, ),
                study_uuid = '',
                name = '',
                uri = '',
                type = '',
        )
        """

    def testFileReference(self):
        """Test FileReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
