# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.bia_study import BIAStudy  # noqa: E501
from openapi_client.rest import ApiException

class TestBIAStudy(unittest.TestCase):
    """BIAStudy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BIAStudy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BIAStudy`
        """
        model = openapi_client.models.bia_study.BIAStudy()  # noqa: E501
        if include_optional :
            return BIAStudy(
                id = '', 
                uuid = '', 
                version = 56, 
                model = openapi_client.models.model_metadata.ModelMetadata(
                    type_name = '', 
                    version = 56, ), 
                title = '', 
                description = '', 
                authors = [
                    openapi_client.models.author.Author(
                        name = '', )
                    ], 
                organism = '', 
                release_date = '', 
                accession_id = '', 
                imaging_type = [
                    ''
                    ], 
                attributes = openapi_client.models.attributes.Attributes(), 
                annotations = [
                    openapi_client.models.study_annotation.StudyAnnotation(
                        author_email = '', 
                        accession_id = '', 
                        key = '', 
                        value = '', 
                        state = 'active', )
                    ], 
                example_image_uri = '', 
                example_image_annotation_uri = '', 
                tags = [
                    ''
                    ], 
                file_references_count = 56, 
                images_count = 56
            )
        else :
            return BIAStudy(
                uuid = '',
                version = 56,
                model = openapi_client.models.model_metadata.ModelMetadata(
                    type_name = '', 
                    version = 56, ),
                title = '',
                description = '',
                organism = '',
                release_date = '',
                accession_id = '',
        )
        """

    def testBIAStudy(self):
        """Test BIAStudy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
