# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_collection_api_private_collections_post(self):
        """Test case for create_collection_api_private_collections_post

        Create Collection  # noqa: E501
        """
        pass

    def test_create_file_reference_api_private_file_references_post(self):
        """Test case for create_file_reference_api_private_file_references_post

        Create File Reference  # noqa: E501
        """
        pass

    def test_create_image_representation_api_private_images_image_uuid_representations_single_post(self):
        """Test case for create_image_representation_api_private_images_image_uuid_representations_single_post

        Create Image Representation  # noqa: E501
        """
        pass

    def test_create_images_api_private_images_bulk_post(self):
        """Test case for create_images_api_private_images_bulk_post

        Create Images  # noqa: E501
        """
        pass

    def test_create_images_api_private_images_post(self):
        """Test case for create_images_api_private_images_post

        Create Images  # noqa: E501
        """
        pass

    def test_create_study_api_private_study_post(self):
        """Test case for create_study_api_private_study_post

        Create Study  # noqa: E501
        """
        pass

    def test_get_collections_api_search_collections_get(self):
        """Test case for get_collections_api_search_collections_get

        Get Collections  # noqa: E501
        """
        pass

    def test_get_image_api_file_references_file_reference_uuid_get(self):
        """Test case for get_image_api_file_references_file_reference_uuid_get

        Get Image  # noqa: E501
        """
        pass

    def test_get_image_api_images_image_uuid_get(self):
        """Test case for get_image_api_images_image_uuid_get

        Get Image  # noqa: E501
        """
        pass

    def test_get_image_ome_metadata_api_images_image_uuid_ome_metadata_get(self):
        """Test case for get_image_ome_metadata_api_images_image_uuid_ome_metadata_get

        Get Image Ome Metadata  # noqa: E501
        """
        pass

    def test_get_studies_for_collection_api_search_studies_get(self):
        """Test case for get_studies_for_collection_api_search_studies_get

        Get Studies For Collection  # noqa: E501
        """
        pass

    def test_get_study_api_study_uuid_get(self):
        """Test case for get_study_api_study_uuid_get

        Get Study  # noqa: E501
        """
        pass

    def test_get_study_file_references_api_study_uuid_file_references_get(self):
        """Test case for get_study_file_references_api_study_uuid_file_references_get

        Get Study File References  # noqa: E501
        """
        pass

    def test_get_study_images_api_study_uuid_images_get(self):
        """Test case for get_study_images_api_study_uuid_images_get

        Get Study Images  # noqa: E501
        """
        pass

    def test_health_check_admin_health_check_get(self):
        """Test case for health_check_admin_health_check_get

        Health Check  # noqa: E501
        """
        pass

    def test_search_images_api_search_images_get(self):
        """Test case for search_images_api_search_images_get

        Search Images  # noqa: E501
        """
        pass

    def test_study_refresh_counts_api_private_studies_study_uuid_refresh_counts_post(self):
        """Test case for study_refresh_counts_api_private_studies_study_uuid_refresh_counts_post

        Study Refresh Counts  # noqa: E501
        """
        pass

    def test_update_file_reference_api_private_file_references_single_patch(self):
        """Test case for update_file_reference_api_private_file_references_single_patch

        Update File Reference  # noqa: E501
        """
        pass

    def test_update_image_api_private_images_single_patch(self):
        """Test case for update_image_api_private_images_single_patch

        Update Image  # noqa: E501
        """
        pass

    def test_update_study_api_private_study_patch(self):
        """Test case for update_study_api_private_study_patch

        Update Study  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
