apiVersion: v1
kind: Secret
metadata:
  name: {{ include "search.fullname" . }}
type: Opaque
stringData:
  elasticConnstring: "https://{{ .Values.search_env.elasticUsername }}:{{ .Values.search_env.elasticPassword }}@{{ .Values.search_env.elasticHostname }}:9200"
