# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.studies_images.post import CreateImagesStudiesImagesPost
from openapi_client.paths.studies_.post import CreateStudyStudiesPost
from openapi_client.paths.studies_study_id_file_references.get import GetFileReferencesStudiesStudyIdFileReferencesGet
from openapi_client.paths.studies_study_id_images_image_id_ome_metadata.get import GetImageOmeMetadataStudiesStudyIdImagesImageIdOmeMetadataGet
from openapi_client.paths.studies_study_id_images.get import GetImagesStudiesStudyIdImagesGet
from openapi_client.paths.studies_.get import GetStudiesStudiesGet
from openapi_client.paths.studies_study_id.get import GetStudyStudiesStudyIdGet
from openapi_client.paths.admin_health_check.get import HealthCheckAdminHealthCheckGet
from openapi_client.paths.studies_search_images_by_alias.get import ImageByAliasStudiesSearchImagesByAliasGet
from openapi_client.paths.admin_pipelines.get import RunningPipelinesAdminPipelinesGet
from openapi_client.paths.studies_study_id_refresh_counts.post import StudyRefreshCountsStudiesStudyIdRefreshCountsPost


class DefaultApi(
    CreateImagesStudiesImagesPost,
    CreateStudyStudiesPost,
    GetFileReferencesStudiesStudyIdFileReferencesGet,
    GetImageOmeMetadataStudiesStudyIdImagesImageIdOmeMetadataGet,
    GetImagesStudiesStudyIdImagesGet,
    GetStudiesStudiesGet,
    GetStudyStudiesStudyIdGet,
    HealthCheckAdminHealthCheckGet,
    ImageByAliasStudiesSearchImagesByAliasGet,
    RunningPipelinesAdminPipelinesGet,
    StudyRefreshCountsStudiesStudyIdRefreshCountsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
