# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.bia_image import BIAImage  # noqa: E501
from openapi_client.rest import ApiException

class TestBIAImage(unittest.TestCase):
    """BIAImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BIAImage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BIAImage`
        """
        model = openapi_client.models.bia_image.BIAImage()  # noqa: E501
        if include_optional :
            return BIAImage(
                id = '', 
                uuid = '', 
                version = 56, 
                model = openapi_client.models.model_metadata.ModelMetadata(
                    type_name = '', 
                    version = 56, ), 
                study_uuid = '', 
                original_relpath = '', 
                name = '', 
                accession_id = '', 
                dimensions = '', 
                representations = [
                    openapi_client.models.bia_image_representation.BIAImageRepresentation(
                        accession_id = '', 
                        size = 56, 
                        uri = [
                            ''
                            ], 
                        type = '', 
                        dimensions = '', 
                        attributes = openapi_client.models.attributes.Attributes(), 
                        rendering = openapi_client.models.rendering_info.RenderingInfo(
                            channel_renders = [
                                openapi_client.models.channel_rendering.ChannelRendering(
                                    colormap_start = [
                                        1.337
                                        ], 
                                    colormap_end = [
                                        1.337
                                        ], 
                                    scale_factor = 1.337, )
                                ], 
                            default_z = 56, 
                            default_t = 56, ), )
                    ], 
                attributes = openapi_client.models.attributes.Attributes(), 
                annotations = [
                    openapi_client.models.image_annotation.ImageAnnotation(
                        author_email = '', 
                        accession_id = '', 
                        key = '', 
                        value = '', 
                        state = 'active', )
                    ], 
                image_aliases = [
                    openapi_client.models.bia_image_alias.BIAImageAlias(
                        name = '', 
                        accession_id = '', )
                    ]
            )
        else :
            return BIAImage(
                uuid = '',
                version = 56,
                model = openapi_client.models.model_metadata.ModelMetadata(
                    type_name = '', 
                    version = 56, ),
                study_uuid = '',
                original_relpath = '',
                accession_id = '',
        )
        """

    def testBIAImage(self):
        """Test BIAImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
