# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.body_search_images_api_search_images_get import BodySearchImagesApiSearchImagesGet  # noqa: E501
from openapi_client.rest import ApiException

class TestBodySearchImagesApiSearchImagesGet(unittest.TestCase):
    """BodySearchImagesApiSearchImagesGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodySearchImagesApiSearchImagesGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodySearchImagesApiSearchImagesGet`
        """
        model = openapi_client.models.body_search_images_api_search_images_get.BodySearchImagesApiSearchImagesGet()  # noqa: E501
        if include_optional :
            return BodySearchImagesApiSearchImagesGet(
                attributes = openapi_client.models.attributes.Attributes(), 
                annotations = [
                    None
                    ]
            )
        else :
            return BodySearchImagesApiSearchImagesGet(
        )
        """

    def testBodySearchImagesApiSearchImagesGet(self):
        """Test BodySearchImagesApiSearchImagesGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
