# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.body_register_user_auth_users_register_post import BodyRegisterUserAuthUsersRegisterPost  # noqa: E501
from openapi_client.rest import ApiException

class TestBodyRegisterUserAuthUsersRegisterPost(unittest.TestCase):
    """BodyRegisterUserAuthUsersRegisterPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyRegisterUserAuthUsersRegisterPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyRegisterUserAuthUsersRegisterPost`
        """
        model = openapi_client.models.body_register_user_auth_users_register_post.BodyRegisterUserAuthUsersRegisterPost()  # noqa: E501
        if include_optional :
            return BodyRegisterUserAuthUsersRegisterPost(
                email = '', 
                password_plain = '', 
                secret_token = ''
            )
        else :
            return BodyRegisterUserAuthUsersRegisterPost(
                email = '',
                password_plain = '',
                secret_token = '',
        )
        """

    def testBodyRegisterUserAuthUsersRegisterPost(self):
        """Test BodyRegisterUserAuthUsersRegisterPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
