# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.bulk_operation_response import BulkOperationResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestBulkOperationResponse(unittest.TestCase):
    """BulkOperationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BulkOperationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkOperationResponse`
        """
        model = openapi_client.models.bulk_operation_response.BulkOperationResponse()  # noqa: E501
        if include_optional :
            return BulkOperationResponse(
                items = [
                    openapi_client.models.bulk_operation_item.BulkOperationItem(
                        status = 56, 
                        idx_in_request = 56, 
                        message = '', )
                    ]
            )
        else :
            return BulkOperationResponse(
                items = [
                    openapi_client.models.bulk_operation_item.BulkOperationItem(
                        status = 56, 
                        idx_in_request = 56, 
                        message = '', )
                    ],
        )
        """

    def testBulkOperationResponse(self):
        """Test BulkOperationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
