services:
  biaint-mongo:
    image: mongo:6.0
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - 27017:27017
    expose:
      - 27017
      # command: "mongod --config /etc/mongo.conf --oplogMinRetentionHours 10"
      # volumes:
      #   - "./.share/mongo.conf:/etc/mongo.conf"
      #     #- "./.share/keyfile.secret:/home/share/keyfile/keyfile.secret"
  bia-integrator-api:
    build: .
    container_name: api
    hostname: api
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - "./.env_compose:/integrator-api/.env"

volumes:
  api_data:
    #? do we always want a 'seed db'?
    #external: true