services:
  biaint-mongo:
    image: mongo:6.0
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - api_data:/data/db
  biaint-api:
    image: ghcr.io/bioimage-archive/integrator-api:0.1
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - "./.env_compose:/integrator-api/.env"

volumes:
  api_data:
    #? do we always want a 'seed db'?
    #external: true