services:
  bia-integrator-mongo:
    image: mongo:6.0
    hostname: mongo1
    container_name: biaint-mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - api_data:/data/db
  bia-integrator-api:
    image: ghcr.io/bioimage-archive/integrator-api:0.1
    container_name: api
    hostname: api
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - "./.env_compose:/integrator-api/.env"

volumes:
  api_data:
    #? do we always want a 'seed db'?
    #external: true