name: Docker Compose Test API
on:
  pull_request:
    branches:
      - main # Trigger the action on pull requests targeting the main branch
      - dev
  push:
    branches:
      - main # Trigger the action on push events to the main branch
      - dev
env:
  MONGO_INITDB_ROOT_PASSWORD: ${{ vars.MONGO_INITDB_ROOT_PASSWORD }}
  MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_INITDB_ROOT_USERNAME }}
jobs:
  docker-compose-test:
    runs-on: ubuntu-latest # Run the job on the latest Ubuntu VM
    defaults:
      run:
        working-directory: ./api # Set the working directory for all run steps in this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout your repository to the GitHub Actions runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # Set up Docker Buildx for building and pushing Docker images
      - name: Cache Docker layers
        uses: actions/cache@v2 # Cache Docker layers to speed up subsequent builds
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Docker Compose Up
        run: |
          docker compose up --build -d  # Build and start your Docker containers in the background
       - name: Run tests
         run: |
           docker compose exec -T api poetry run pytest
      - name: Docker Compose Down
        run: |
          docker compose down  # Stop and remove your Docker containers
