name: CI
on: [pull_request, push]

jobs:
  ci-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.4.2"]
        os: [ubuntu-20.04, macos-latest, windows-latest]
        project:
          [
            bia-ingest,
            bia-shared-datamodels,
            core,
          ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help
      - name: Poetry env setup
        run: poetry env use python
      - name: Poetry install
        run: poetry install
      - name: Check to see if poetry can build
        run: poetry build
      - name: Run pytest
        run: poetry run pytest
  ci-make:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.4.2"]
        os: [ubuntu-20.04, macos-latest, windows-latest] 
        project:
          [
            bia-export,
          ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run poetry image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Set up Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install docker 
          brew services start docker
      - name: Verify Docker is installed
        run: docker --version
      - name: Docker Compose Up
        run: docker compose up -d --build    
      - name: set up poetry
        run: |
          poetry env use python
          poetry install
      - name: Check to see if poetry can build
        run: poetry build
      - name: Run pytest
        run: poetry run pytest
      # Always cleanup - even for cancelled jobs
      - name: Docker Compose Down
        run: |
          docker compose down
        if: ${{ always() }}

