name: Publish Docker
on:
  push:
    branches:
      - main
      - master
  pull_request: ~
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api # Set the working directory for all run steps in this job
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 2
      - name: Detect and tag new version
        id: check-version
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          create-tag: false # Do not create new tag
          version-command: |
            make api.version
      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image (version tag)
        if: steps.check-version.outputs.current-version
        uses: docker/build-push-action@v4.2.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.check-version.outputs.current-version }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image (latest tag)
        if: steps.check-version.outputs.current-version
        uses: docker/build-push-action@v4.2.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
