apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
type: Opaque
stringData:
  mongoConnstring: "mongodb://{{ .Values.api_env.mongoRootUser }}:{{ .Values.api_env.mongoRootPassword }}@{{ .Values.api_env.mongoHost }}:27017"
  jwtSecretKey: {{ .Values.api_env.jwtSecretKey }}
  userCreateSecretToken: {{ .Values.api_env.userCreateSecretToken }}
  elasticConnstring: "http://{{ .Values.api_env.elasticUsername }}:{{ .Values.api_env.elasticPassword }}@{{ .Values.api_env.elasticHostname }}:9200"